[project]
name = "mics-cvia-spark-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.3",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
