download:
  data_dir: "data"
  streams:
    stream1: "https://uniluxembourg-my.sharepoint.com/:u:/g/personal/0200566850_uni_lu/EbTNBxOOdhxNoZC-mtqnfL8BW705Gold48M6p6kLhaPy9w?download=1"
    stream2: ""
  stream_dirs:
    stream1: "stream1"
    stream2: "stream2"
dataset:
  image_width: 1024
  image_height: 1024
  class_map:
    proba_2: 0
    cheops: 1
    debris: 2
    double_star: 3
    earth_observation_sat_1: 4
    lisa_pathfinder: 5
    proba_3_csc: 6
    proba_3_ocs: 7
    smart_1: 8
    soho: 9
    xmm_newton: 10
pipeline:
  frameworks:
    yolo:
      model_input: "yolo11n.pt"
      dataset_metadata: "./data/stream1/stream1.yaml"
      input_size: [1024, 1024]
      train: 
        epochs: 100
        batch: 200
      test:
        source: "./data/stream1/images/test/"
        output: "./data/stream1/prediction/predictions.csv"
