download:
  data_dir: "../datasets/"
  streams:
    stream1: "https://uniluxembourg-my.sharepoint.com/:u:/g/personal/0200566850_uni_lu/EbTNBxOOdhxNoZC-mtqnfL8BW705Gold48M6p6kLhaPy9w?download=1"
    stream2: ""
  stream_dirs:
    stream1: "stream1"
    stream2: "stream2"

dataset:
  image_width: 1024
  image_height: 1024
  class_map:
    proba_2: 0
    cheops: 1
    debris: 2
    double_star: 3
    earth_observation_sat_1: 4
    lisa_pathfinder: 5
    proba_3_csc: 6
    proba_3_ocs: 7
    smart_1: 8
    soho: 9
    xmm_newton: 10
    
pipeline:
  yolo:
    model_input: "yolo11x.pt"
    # model_input: "/mnt/aiongpfs/users/pbastossoares/spark/runs/detect/train10/weights/best.pt"
    dataset_metadata: "/mnt/aiongpfs/users/pbastossoares/datasets/stream1.yaml"
    input_size: [1024, 1024] # Matches the image size of the dataset
    train: 
      epochs: 50
      batch: 0.95
      optimizer: SGD
      cos_lr: true
      lr0: 0.001
      lrf: 0.0001
      augment: false
      patience: 10 # Wait for 10 epochs for early stopping
      dropout: 0.0
      save_period: 5 # Save a snapshot every 5 epochs
      device: [0]
    test:
        source: "/mnt/aiongpfs/users/pbastossoares/datasets/stream1/images/test/"
        output: "./data/submission.csv"
