download:
  data_dir: "data"
  streams:
    stream1: "https://uniluxembourg-my.sharepoint.com/:u:/g/personal/0200566850_uni_lu/EbTNBxOOdhxNoZC-mtqnf"
    stream2: ""
  stream_dirs:
    stream1: "stream1"
    stream2: "stream2"
dataset:
  image_width: 1024
  image_height: 1024
  class_map:
    proba_2: 0
    cheops: 1
    debris: 2
    double_star: 3
    earth_observation_sat_1: 4
    lisa_pathfinder: 5
    proba_3_csc: 6
    proba_3_ocs: 7
    smart_1: 8
    soho: 9
    xmm_newton: 10
pipeline:
  frameworks:
    yolo:
      input_size: [1024, 1024]
      epochs: 2
